/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/change-password/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change user password
     * @description Validates current password and updates to new password, invalidating older tokens.
     */
    post: operations["auth_change_password_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User login
     * @description Authenticates user with email and password, returning tokens and dashboard config.
     */
    post: operations["auth_login_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User logout
     * @description Blacklists the provided refresh token.
     */
    post: operations["auth_logout_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user profile
     * @description Returns profile information for the authenticated caller.
     */
    get: operations["auth_me_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update current user profile
     * @description Updates full_name and/or phone for the authenticated caller. Rejects privileged fields.
     */
    patch: operations["auth_me_partial_update"];
    trace?: never;
  };
  "/api/auth/refresh/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh access token
     * @description Issues a fresh access token given a valid refresh token.
     */
    post: operations["auth_refresh_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Returns the operational status of the FitGate backend service.
     */
    get: operations["health_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/platform/super-admins/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create additional Super Admin
     * @description Creates a new Super Admin account. Requires active Super Admin credentials.
     */
    post: operations["platform_super_admins_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Payload for changing user password. */
    ChangePasswordRequestRequest: {
      current_password: string;
      new_password: string;
    };
    /** @description Response containing refreshed JWT pair and user summary. */
    ChangePasswordResponse: {
      access: string;
      refresh: string;
      user: components["schemas"]["UserSummary"];
    };
    /** @description Payload for creating an additional Super Admin account. */
    CreateSuperAdminRequestRequest: {
      /** Format: email */
      email: string;
      password: string;
      current_password: string;
    };
    HealthCheckResponse: {
      /** @default ok */
      status: string;
      /** @default FitGate API */
      app: string;
    };
    /** @description Payload for user authentication. */
    LoginRequestRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    /** @description Response containing JWT tokens, user summary, and role dashboard. */
    LoginResponse: {
      access: string;
      refresh: string;
      user: components["schemas"]["UserSummary"];
      dashboard: {
        [key: string]: unknown;
      };
    };
    /** @description Payload for user logout. */
    LogoutRequestRequest: {
      refresh: string;
    };
    /** @description Payload for updating user profile (full_name and phone only). */
    PatchedUserProfileUpdateRequest: {
      full_name?: string;
      phone?: string;
    };
    /**
     * @description * `super_admin` - Super Admin
     *     * `owner` - Owner
     *     * `manager` - Manager
     *     * `trainer` - Trainer
     *     * `reception` - Reception
     *     * `member` - Member
     * @enum {string}
     */
    RoleEnum:
      "super_admin" | "owner" | "manager" | "trainer" | "reception" | "member";
    /** @description Response for created Super Admin. */
    SuperAdminResponse: {
      /** Format: uuid */
      readonly id: string;
      /** Format: email */
      readonly email: string;
      readonly role: components["schemas"]["RoleEnum"];
      readonly must_change_password: boolean;
      /** Format: date-time */
      readonly created_at: string;
    };
    /** @description Payload for token refresh. */
    TokenRefreshRequestRequest: {
      refresh: string;
    };
    /** @description Response containing refreshed access token. */
    TokenRefreshResponse: {
      access: string;
    };
    /** @description Profile representation of authenticated user. */
    UserProfile: {
      /** Format: uuid */
      readonly id: string;
      /** Format: email */
      readonly email: string;
      readonly role: components["schemas"]["RoleEnum"];
      /** Format: uuid */
      readonly gym_id: string | null;
      readonly full_name: string;
      readonly phone: string;
      readonly must_change_password: boolean;
    };
    /** @description Minimal representation of authenticated user. */
    UserSummary: {
      /** Format: uuid */
      readonly id: string;
      /** Format: email */
      readonly email: string;
      readonly role: components["schemas"]["RoleEnum"];
      /** Format: uuid */
      readonly gym_id: string | null;
      readonly full_name: string;
      readonly phone: string;
      readonly must_change_password: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_change_password_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["ChangePasswordRequestRequest"];
        "multipart/form-data": components["schemas"]["ChangePasswordRequestRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ChangePasswordResponse"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_login_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["LoginRequestRequest"];
        "multipart/form-data": components["schemas"]["LoginRequestRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_logout_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoutRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["LogoutRequestRequest"];
        "multipart/form-data": components["schemas"]["LogoutRequestRequest"];
      };
    };
    responses: {
      /** @description Successfully logged out */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid refresh token */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserProfile"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Password change required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_me_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUserProfileUpdateRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedUserProfileUpdateRequest"];
        "multipart/form-data": components["schemas"]["PatchedUserProfileUpdateRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserProfile"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Password change required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  auth_refresh_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefreshRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequestRequest"];
        "multipart/form-data": components["schemas"]["TokenRefreshRequestRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenRefreshResponse"];
        };
      };
      /** @description Invalid or expired refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  health_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthCheckResponse"];
        };
      };
    };
  };
  platform_super_admins_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSuperAdminRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["CreateSuperAdminRequestRequest"];
        "multipart/form-data": components["schemas"]["CreateSuperAdminRequestRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuperAdminResponse"];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
