# Generated by Django 5.2.17 on 2026-10-07 10:03

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.tenants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GymTenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "subdomain",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[apps.tenants.models.validate_subdomain],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("pro", "Pro"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="ETB", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gym Tenant",
                "verbose_name_plural": "Gym Tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GymConfig",
            fields=[
                (
                    "gym",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="config",
                        serialize=False,
                        to="tenants.gymtenant",
                    ),
                ),
                ("has_trainer_module", models.BooleanField(default=False)),
                ("has_ai_plans", models.BooleanField(default=False)),
                ("has_analytics", models.BooleanField(default=False)),
                ("has_group_classes", models.BooleanField(default=False)),
                ("has_multi_branch", models.BooleanField(default=False)),
                (
                    "chapa_merchant_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("freeze_days_allowed", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Gym Configuration",
                "verbose_name_plural": "Gym Configurations",
            },
        ),
    ]
